### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jacebrowning** [danieldiekmeier/memegenerator#1]
Your notes say "feel free to use". Can you add a license file to explicitly grant this permission?

MIT is a good choice if want a copyright attached: https://tldrlegal.com/license/mit-license

WTFPL is a good choice if you don't care: https://tldrlegal.com/license/do-wtf-you-want-to-public-license-v2-(wtfpl-2.0)

**Comment by danieldiekmeier** [comment]
Just did that, it's explicitly MIT now. (See LICENSE.md)
